/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JvAmbulanceWlList {
    }
}
declare global {
    interface HTMLJvAmbulanceWlListElement extends Components.JvAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLJvAmbulanceWlListElement: {
        prototype: HTMLJvAmbulanceWlListElement;
        new (): HTMLJvAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "jv-ambulance-wl-list": HTMLJvAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface JvAmbulanceWlList {
    }
    interface IntrinsicElements {
        "jv-ambulance-wl-list": JvAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jv-ambulance-wl-list": LocalJSX.JvAmbulanceWlList & JSXBase.HTMLAttributes<HTMLJvAmbulanceWlListElement>;
        }
    }
}
